baseURL = 'https://laesquinagris.com/'
languageCode = 'es-mx'
title = 'La Esquina Gris'
theme = 'PaperMod'
paginate = 5

# Build Options
enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false

# Asset minification
[minify]
disableXML = true
minifyOutput = true

# Parameters
[params]
env = "production"
title = "La Esquina Gris - Escribo un blog por terapia"
description = "Blog de personal habland de tecnolog칤a como Gnu/Linux, lenguajes de programaci칩n y pensamientos que rondan la cabeza de un programador."
keywords = [ "Blog", "Portfolio", "VentGrey", "Omar Jair Purata Funes", "La Esquina Gris", "Blog de Linux en espa침ol", "blog de tecnolog칤a en espa침ol", "blog de linux en espa침ol", "blog de devops en espa침ol", "noticias de tecnolog칤a en espa침ol", "noticias de linux en espa침ol", "noticias devops en espa침ol", "blogs de tecnolog칤a en espa침ol", "blogs de linux in English", "blogs devops en espa침ol", "nginx blog espa침ol", "blog de sysadmin para programadores", "blog de programaci칩n", "tutoriales de C", "Tutoriales de Rust", "Tutoriales de Svelte", "diario de sistemas para principiantes", "tareas de administrador de sistemas para principiantes en espa침ol", "discusi칩n sobre tareas de administrador de sistemas para principiantes en espa침ol", "gu칤a para tareas del administrador de sistemas" ]
author = "VentGrey"
images = [ "img/laesquinagris.png" ]
DateFormat = "January 2, 2006"
defaultTheme = "auto"
disableThemeToggle = false
ShowReadingTime = true
ShowShareButtons = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
ShowWordCount = true
ShowRssButtonInSectionTermList = true
UseHugoToc = true
disableSpecial1stPost = false
disableScrollToTop = false
comments = false
hidemeta = false
hideSummary = false
showtoc = false
tocopen = false
ShareButtons = ["linkedin", "twitter", "reddit", "facebook", "whatsapp", "telegram"]

  [params.assets]
  favicon = "favicon.ico"
  apple_touch_icon = "apple-touch-icon.png"
  safari_pinned_tab = "https://laesquinagris.com/"

  [params.label]
  text = "La Esquina Gris"
  icon = "/apple-touch-icon.png"
  iconHeight = 35

  [params.profileMode]
  enabled = true
  title = "La Esquina Gris"
  subtitle = "Bienvenid@ a mi blog de tecnolog칤a por terapia."
  imageUrl = "img/profile.jpeg"
  imageWidth = 120
  imageHeight = 120
  imageTitle = "yo mero"

    [[params.profileMode.buttons]]
    name = "Blog"
    url = "posts"

    [[params.profileMode.buttons]]
    name = "Portafolio de Trabajo"
    url = "pages/resume"

    [[params.profileMode.buttons]]
    name = "Herramientas Grises"
    url = "pages/ventools"

  [params.homeInfoParams]
  Title = "Puedo ver tu casa desde aqu칤 游뿛"
  Content = "Bienvenid@ a mi blog de tecnolog칤a por terapia."

  [[params.socialIcons]]
  name = "twitter"
  url = "https://twitter.com/VentGrey"

  [[params.socialIcons]]
  name = "github"
  url = "https://github.com/VentGrey"

  [[params.socialIcons]]
  name = "kofi"
  url = "https://ko-fi.com/ventgrey"

  [[params.socialIcons]]
  name = "email"
  url = "mailto:ventgrey@gmail.com?subject=Contacto%20a%20trav%C3%A9s%20de%20tu%20blog.&body=%C2%A1Hola!%20Le%C3%AD%20tu%20blog%20y%20me%20gustar%C3%ADa%20contactarte."

  [[params.socialIcons]]
  name = "liberapay"
  url = "https://liberapay.com/VentGrey"

  [[params.socialIcons]]
  name = "lastfm"
  url = "https://www.last.fm/user/omarpurataf/library"

  [[params.socialIcons]]
  name = "linkedin"
  url = "https://www.linkedin.com/in/omar-jair-purata-funes/"

  [[params.socialIcons]]
  name = "medium"
  url = "https://medium.com/@omarpurataf_53869"

  [[params.socialIcons]]
  name = "paypal"
  url = "https://paypal.me/VentGrey?country.x=MX&locale.x=es_XC"

  [[params.socialIcons]]
  name = "spotify"
  url = "https://open.spotify.com/user/22ikuvunhe6y36x6lzdbfxywi?si=82e22671c75740b0"

  [[params.socialIcons]]
  name = "telegram"
  url = "tg://resolve?domain=VentGrey"

  [[params.socialIcons]]
  name = "other"
  url = "https://upvent.codes/"

  [params.cover]
  hidden = true
  hiddenInList = true
  hiddenInSingle = true

  [params.editPost]
  URL = "https://github.com/VentGrey/ventgrey.github.io/issues"
  Text = "Sugerir cambios"
  appendFilePath = true

  [params.fuseOpts]
  isCaseSensitive = false
  shouldSort = true
  location = 0
  distance = 1_000
  threshold = 0.4
  minMatchCharLength = 0
  keys = [ "title", "permalink", "summary", "content" ]

pygmentsUseClasses = true

[[menu.main]]
identifier = "categories"
name = "Categorias"
url = "/categories/"
weight = 10

[[menu.main]]
identifier = "tags"
name = "Etiquetas"
url = "/tags/"
weight = 20

[[menu.main]]
identifier = "example"
name = "쯅ecesitas una consulta?"
url = "https://ko-fi.com/ventgrey"
weight = 30

[[menu.main]]
identifier = "new"
name = "Pr칩ximos art칤culos"
url = "/upcoming/posts"
weight = 40

[markup.highlight]
noClasses = false
